#!/bin/bash -e

MAX_COMMAND_WAIT_TIME=10

log() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

fail() {
  log "$@"
  exit 1
}

run() {
  log "Running $@..."
  timeout "${MAX_COMMAND_WAIT_TIME}" "$@" 1>&2 || fail "$1 invocation failed"
}

output_file() {
  # Output file length as unsigned 32-bit integer
  printf '%08x' "$(wc -c "$1" | cut -d' ' -f1)" | xxd -r -p
  # Output raw file bytes
  cat "$1"
}

cd /tmp

cat > render.tex
run latex -halt-on-error -interaction=nonstopmode render.tex 1>&2
run dvisvgm --no-fonts --verbosity=1 render.dvi 1>&2
run rsvg-convert -o render.png render.svg 1>&2

[ -f render.png ] || fail 'PNG was not generated'
[ "$(wc -c render.png | cut -d' ' -f1)" -ge 24 ] || fail 'PNG file too small'
[ "$(xxd -p -l4 render.png)" = '89504e47' ] || fail 'no PNG magic number found'
[ "$(xxd -p -l4 -s12 render.png)" = '49484452' ] || fail 'no IHDR in PNG'

# Output: binary width followed by height as unsigned 32-bit integer
dd if=render.png skip=4 bs=4 count=2 status=none

output_file 'render.svg'
output_file 'render.png'
